export const demoEvents = [
  {
    slug: 'blankets-and-wine-nairobi',
    title: 'Blankets & Wine Nairobi',
    location: 'Uhuru Gardens, Nairobi',
    date: '2026-07-04',
    price: 'From KES 2,500',
    description: 'A premium outdoor music, food, fashion, and culture experience built for Nairobi weekends.',
  },
  {
    slug: 'koroga-festival-2025',
    title: 'Koroga Festival 2025',
    location: 'The Carnivore Grounds',
    date: '2026-07-18',
    price: 'From KES 3,000',
    description: 'Live performances, curated food vendors, VIP lounges, sponsor activations, and citywide event energy.',
  },
  {
    slug: 'sauti-sol-live-in-concert',
    title: 'Sauti Sol Live in Concert',
    location: 'KICC, Nairobi',
    date: '2026-08-01',
    price: 'From KES 4,000',
    description: 'A polished concert night with ticketing, transport, food pre-orders, and event-day wallet access.',
  },
  {
    slug: 'nairobi-comedy-night',
    title: 'Nairobi Comedy Night',
    location: 'The Standup Lounge',
    date: '2026-07-25',
    price: 'From KES 1,200',
    description: 'A premium comedy showcase for Nairobi audiences with reserved seating and social sharing.',
  },
  {
    slug: 'nairobi-jazz-festival-2027',
    title: 'Nairobi Jazz Festival 2027',
    location: 'KICC, Nairobi',
    date: '2027-02-14',
    price: 'From KES 2,500',
    description: 'A premium city festival with ticketing, Foodo pre-orders, Triplink shuttles, and event-day wallet passes.',
  },
  {
    slug: 'gospel-sundown-live',
    title: 'Gospel Sundown Live',
    location: 'Uhuru Gardens',
    date: '2027-03-01',
    price: 'From KES 1,500',
    description: 'Community-first gospel event with sponsor activations, food vendors, and transport routes.',
  },
  {
    slug: 'east-africa-tech-summit',
    title: 'East Africa Tech Summit',
    location: 'Sarit Expo Centre',
    date: '2027-04-18',
    price: 'From KES 4,000',
    description: 'Conference operations, staff scheduling, sponsor marketplace, and attendee experience in one OS.',
  },
];

export const adminMetrics = [
  ['Total Users', '18.4K'],
  ['Tickets Sold', '92.7K'],
  ['Revenue', 'KES 148M'],
  ['Active Events', '312'],
  ['Food Revenue', 'KES 18M'],
  ['Transport Revenue', 'KES 11M'],
  ['Merch Revenue', 'KES 7M'],
  ['Sponsor Revenue', 'KES 23M'],
];

export const realtimeTables = [
  'ticket_orders',
  'event_comments',
  'community_posts',
  'food_orders',
  'transport_bookings',
  'vendor_bookings',
  'sponsor_applications',
  'staff_shifts',
  'workspace_messages',
  'notifications',
];
